### ISSUE TITLE
Queue management

### ISSUE THREAD

**Issue by orangespaceman** [MadeByLoosers/noise-box#18]
Display a list of queued tracks

Allow users to delete tracks from the queue, and/or reorder the queue

**Comment by jedrichards** [comment]
At the moment NBModel.js (which represents a single noise box in the model) only has one string `track` representing the current track being played. When this string is changed the server broadcasts an instruction to all pages hosting the noise box to play the MP3.

With queuing, each NBModel will instead have to maintain a playlist. So we'll need to add a NBTrackCollection (i.e. the playlist), which contains many NBTrack models. When the NBTrackCollection is manipulated by a client (i.e. a track added or deleted) the updated playlist should be broadcasted to all listening hosts.

Hosts are free to just move through the playlist at their own speed, we're not worrying about them getting out of sync. With the exception that if the track that the host has been currently playing is removed the host should stop playing the track and move onto the next one, if available.

Since clients can add the same track many times sequentially we'll have to add and remove NBTrack models from the collection via unique id (auto-generated by Backbone as `cid` I think) not by track name, which won't be unique.

**Comment by jedrichards** [comment]
This is sorta done, make a new issue if something about the current queue display isn't quite right ...
