### ISSUE TITLE
Consider limiting to a single host per 'room'

### ISSUE THREAD

**Issue by orangespaceman** [MadeByLoosers/noise-box#30]
There are some limitations in the stats we can display on the client view due to having multiple hosts per room. 

E.G. You can't display the current status in the client windows because it could be different for each host.  So you can't keep track of the currently playing track (or time). 

If we limited it to a single host per room we could eliminate these issues.

Although we are currently supporting multiple hosts, we don't do much by way of concurrency / syncing, other than telling each host that new tracks have been added. 

Opinions?

**Comment by orangespaceman** [comment]
One option could be to display this information when there is only a single host, but not for multiple hosts...

**Comment by jedrichards** [comment]
Yeah, me and Mike discussed this briefly last night. If we had a 1:1 relationship between noise boxes and hosts then we could show accurate/rich information to all the clients since we could model the noise box accurately on the server based on events coming back from the single host.

I still think its fun to have loads of hosts open though.

Perhaps we could say that the first host to connect is the "master" host, and we just listen to events from that host in order to model the noise box and update the clients. We'd either stop the other hosts sending events, or just ignore them. If the master host disconnects we promote the next host in line?

**Comment by orangespaceman** [comment]
Maybe we limit it to a single host, but any client who connects can turn on a 'broadcast' mode, in which case they play the sounds too?

**Comment by jedrichards** [comment]
Yeah, that would work too. That would mean having to include the audio playing functionality in all of the clients as well as the hosts. Plus we'd have to add server logic to broadcast playlist queue changes to all broadcasting clients as well as enforcing a single host. All totally possible though.

But "broadcast mode" is only a click away from every client as it stands anyway with no code changes, just clink on a link to `/host/boxname` ...

I'm not sure, but I think just using the first host to connect as the host to model the 'box, and all subsequent hosts as dumb broadcasters would be the simplest way to get what we want (proper stats for the clients) ... ?

**Comment by orangespaceman** [comment]
Sounds good, I agree for now we should go with the first host being the 'master' host that supplies information back to the model (and on to the user), while all other hosts are just treated as dumb broadcasters.

**Comment by jedrichards** [comment]
We're not worrying about this for now, just let all the hosts play, get out of sync whatevs
